export const countriesFlag =
  [
    { name: "Argentina", flagUrl: "https://flagcdn.com/ar.svg" },
    { name: "Brazil", flagUrl: "https://flagcdn.com/br.svg" },
    { name: "Croatia", flagUrl: "https://flagcdn.com/hr.svg" },
    { name: "Czechia", flagUrl: "https://flagcdn.com/cz.svg" },
    { name: "England", flagUrl: "https://flagcdn.com/gb.svg" },
    { name: "France", flagUrl: "https://flagcdn.com/fr.svg" },
    { name: "Germany", flagUrl: "https://flagcdn.com/de.svg" },
    { name: "West Germany", flagUrl: "https://flagcdn.com/de.svg" },
    { name: "Italy", flagUrl: "https://flagcdn.com/it.svg" },
    { name: "Netherlands", flagUrl: "https://flagcdn.com/nl.svg" },
    { name: "Poland", flagUrl: "https://flagcdn.com/pl.svg" },
    { name: "Portugal", flagUrl: "https://flagcdn.com/pt.svg" },
    { name: "Spain", flagUrl: "https://flagcdn.com/es.svg" },
    { name: "Sweden", flagUrl: "https://flagcdn.com/se.svg" },
    { name: "Uruguay", flagUrl: "https://flagcdn.com/uy.svg" },
    { name: "Belgium", flagUrl: "https://flagcdn.com/be.svg" },
    { name: "Turkey", flagUrl: "https://flagcdn.com/tr.svg" },
    { name: "Austria", flagUrl: "https://flagcdn.com/at.svg" },
    { name: "Chile", flagUrl: "https://flagcdn.com/cl.svg" },
    { name: "Hungary", flagUrl: "https://flagcdn.com/hu.svg" },
    { name: "United States", flagUrl: "https://flagcdn.com/us.svg" },
    { name: "South Africa", flagUrl: "https://flagcdn.com/za.svg" },
    { name: "Switzerland", flagUrl: "https://flagcdn.com/ch.svg" },
    { name: "Qatar", flagUrl: "https://flagcdn.com/qa.svg" },
    { name: "Russia", flagUrl: "https://flagcdn.com/ru.svg" },
    { name: "South Korea", flagUrl: "https://flagcdn.com/kr.svg" },
    { name: "Japan", flagUrl: "https://flagcdn.com/jp.svg" },
    { name: "Mexico", flagUrl: "https://flagcdn.com/mx.svg" }
  ];
